openapi: 3.1.0
info:
  version: 1.0.0
  title: event-notification plugin
  description: |
    This is the specification of the 'event-notification' plugin.
  contact:
    email: info@common-api.ch
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://webhook-notification.common-api.ch
externalDocs:
  description: Find out more about SFTI API specifications.
  url: https://www.common-api.ch
tags:
  - name: event subscriptions
    description: Event subscription operations.
  - name: event notifications
    description: Event notification operations.
security: []
webhooks:
  eventNotification:
    $ref: webhooks/event-notifications.yaml
paths:
  /event-subscriptions:
    $ref: paths/event-subscriptions.yaml
  /event-subscriptions/{eventSubscriptionId}:
    $ref: paths/event-subscriptions_{eventSubscriptionId}.yaml
  /event-subscriptions/{eventSubscriptionId}/event-notifications:
    $ref: paths/event-subscriptions_{eventSubscriptionId}_event-notifications.yaml
components:
  schemas: {}
  responses: {}
  parameters: {}
  headers: {}
  securitySchemes: {}
