openapi: 3.0.0
info:
  version: 1.0.0
  title: event-notification webhook
  description: |
    This is the specification of the 'event-notification' webhook. Disclaimer:
      - This specification file is to be interpreted as pseudo-code
      - once the structure and endpoints are agreed<
        * all mandatory and optional headers will have to be added
        * all error responses will have to be specified
        * example requests/responses will need to be improved
        * missing details in descriptions will have to be added
  contact:
    email: info@common-api.ch
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://webhook-notification.common-api.ch
security: []
paths:
  /event-notifications:
    $ref: paths/event-notifications.yaml
