openapi: 3.0.0
info:
  version: 1.0.0
  title: event-notification webhook
  description: >
    This is the specification of the 'event-notification' webhook.
    Disclaimer:
      - This specification file is to be interpreted as pseudo-code
      - once the structure and endpoints are agreed<
        * all mandatory and optional headers will have to be added
        * all error responses will have to be specified
        * example requests/responses will need to be improved
        * missing details in descriptions will have to be added
  contact:
    email: info@common-api.ch
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://webhook-notification.common-api.ch
paths:
  /event-notifications:
    post:
      description: Send notification
      parameters:
        - $ref: '#/components/parameters/correlation_in_header'
        - $ref: '#/components/parameters/api_version_in_header'
        - $ref: '#/components/parameters/event_type_in_header'
        - $ref: '#/components/parameters/event_id_in_header'
        - $ref: '#/components/parameters/event_created_in_header'
        - $ref: '#/components/parameters/event_subscription_id_in_header'
      tags:
        - Notification Webhook
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventNotification'
      responses:
        '202':
          description: event-notification accepted
          headers:
            X-Correlation-ID:
              $ref: '#/components/headers/X-Correlation-ID'
        '400':
          $ref: '#/components/responses/standard400'
        '404':
          $ref: '#/components/responses/standard404'
        '405':
          $ref: '#/components/responses/standard405'
        '429':
          $ref: '#/components/responses/standard429'
        '500':
          $ref: '#/components/responses/standard500'
        '501':
          $ref: '#/components/responses/standard501'
        '503':
          $ref: '#/components/responses/standard503'
        '504':
          $ref: '#/components/responses/standard504'
components:
  parameters:
    correlation_in_header:
      name: X-Correlation-ID
      in: header
      description: >-
        Unique ID (defined by the caller) which will be reflected back in the
        response.
      required: true
      schema:
        type: string
        maxLength: 64
    api_version_in_header:
      name: X-CorApi-API-Version
      in: header
      description: The API Version
      example: '1.0'
      required: false
      schema:
        type: string
    event_type_in_header:
      name: X-CorApi-Event-Type
      in: header
      description: The Event-Type
      example: Order:Created
      required: false
      schema:
        type: string
    event_id_in_header:
      name: X-CorApi-Event-ID
      in: header
      description: The Event-ID
      example: 7c5f40fc-1b29-4263-a2dd-e127a22a947f
      required: false
      schema:
        type: string
    event_created_in_header:
      name: X-CorAPI-Event-Created-At
      in: header
      description: The Event-Created Date
      example: '2024-05-28T13:44:53Z'
      required: false
      schema:
        type: string
        format: date-time
    event_subscription_id_in_header:
      name: X-CorApi-Event-Subscription-ID
      in: header
      description: The ID of the Subscription the event was created for
      example: 7c5f40fc-1b29-4263-a2dd-e127a22a947f
      required: false
      schema:
        type: string
  headers:
    X-Correlation-ID:
      description: >-
        Client defined ID from request to correlate HTTP requests between a
        client and a server
      schema:
        type: string
        maxLength: 64
        example: f058ebd6-02f7-4d3f-942e-904344e8cde5
  schemas:
    EventNotification:
      type: object
      properties:
        version:
          type: string
          example: '1.0'
        eventType:
          type: string
          example: Order:Partially_Filled
        eventSubscriptionId:
          type: string
          example: 7c5f40fc-1b29-4263-a2dd-e127a22a947f
        resourceLink:
          type: string
          example: /api/bankingservices/b-link/order-placement/v1/orders/abcd1234
        createdAt:
          type: string
          format: date-time
          example: 2022-10-26T07:58:30.996+0100
        id:
          type: string
          example: 120066c9-58a1-432b-aa60-712fae7f143e
    commonErrorResponse:
      title: Common Error Response
      type: object
      properties:
        type:
          $ref: '#/components/schemas/commonErrorType'
        title:
          type: string
          example: This is the general problem description
        detail:
          type: string
          example: Detailed problem description with respect to the current request
        instance:
          type: string
          example: path/to/corresponding/resource
    commonErrorType:
      title: Common Error Type
      type: string
      description: >-
        Error Types for commonErrorResponse. See Appendix for detailed
        information.
      example: /problems/TECHNICAL_ERROR
      enum:
        - /problems/INVALID_PAYLOAD
        - /problems/MALFORMED_PAYLOAD
        - /problems/TECHNICAL_ERROR
        - /problems/FILE_NOT_FOUND
        - /problems/SUBSCRIPTION_NOT_FOUND
        - /problems/INSUFFICIENT_PRIVILEGES
        - /problems/SUBSCRIPTION_ALREADY_EXISTS
        - /problems/TOO_MANY_REQUESTS
        - /problems/METHOD_NOT_ALLOWED
  responses:
    standard400:
      headers:
        X-Correlation-ID:
          $ref: '#/components/headers/X-Correlation-ID'
      description: Bad Request - The format of the request was invalid.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/commonErrorResponse'
          example:
            type: /problems/INVALID_PAYLOAD
            title: the request body was invalid
            detail: ...
            instance: path/to/corresponding/resource
    standard404:
      headers:
        X-Correlation-ID:
          $ref: '#/components/headers/X-Correlation-ID'
      description: >-
        Not Found - Either the endpoint does not exist or a requested resource
        is not available
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/commonErrorResponse'
          example:
            type: /problems/SUBSCRIPTION_NOT_FOUND
            title: resource not found
            detail: ...
            instance: path/to/corresponding/resource
    standard405:
      headers:
        X-Correlation-ID:
          $ref: '#/components/headers/X-Correlation-ID'
      description: >-
        Method Not Allowed - The request method is known by the server but is
        not supported by the target resource
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/commonErrorResponse'
          example:
            type: /problems/METHOD_NOT_ALLOWED
            title: method not allowed
            detail: ...
            instance: path/to/corresponding/resource
    standard429:
      headers:
        X-Correlation-ID:
          $ref: '#/components/headers/X-Correlation-ID'
      description: >
        When an SP (in the role of the notification sender) sends too many
        notification requests in a given amount of time the SU (in the role of
        the notification recipient) shall 

        respond with HTTP 429 (Too many requests). This response may contain a
        Retry-After header 

        indicating how long the SP must wait before making a new request. (see
        https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429).
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/commonErrorResponse'
          example:
            type: /problems/TOO_MANY_REQUESTS
            title: resource not found
            detail: ...
            instance: path/to/corresponding/resource
    standard500:
      headers:
        X-Correlation-ID:
          $ref: '#/components/headers/X-Correlation-ID'
      description: Internal Server Error
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/commonErrorResponse'
          example:
            type: /problems/TECHNICAL_ERROR
            title: unexpected error occurred
            detail: ...
            instance: path/to/corresponding/resource
    standard501:
      headers:
        X-Correlation-ID:
          $ref: '#/components/headers/X-Correlation-ID'
      description: >-
        Not Implemented - The request method is not supported by the server and
        cannot be handled.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/commonErrorResponse'
          example:
            type: /problems/TECHNICAL_ERROR
            title: unexpected error occurred
            detail: ...
            instance: path/to/corresponding/resource
    standard503:
      headers:
        X-Correlation-ID:
          $ref: '#/components/headers/X-Correlation-ID'
      description: Service Unavailable
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/commonErrorResponse'
          example:
            type: /problems/TECHNICAL_ERROR
            title: server unavailable
            detail: ...
            instance: path/to/corresponding/resource
    standard504:
      headers:
        X-Correlation-ID:
          $ref: '#/components/headers/X-Correlation-ID'
      description: Gateway Timeout
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/commonErrorResponse'
          example:
            type: /problems/TECHNICAL_ERROR
            title: server unavailable
            detail: ...
            instance: path/to/corresponding/resource
